### PR TITLE
 Add support for PHP 7.3+ and 8.0+

### PR DESCRIPTION
**Pull request by xvilo**
We would like to fully upgrade our project to PHP 8.0 and have been running this for a couple of months without issues

### CODE REVIEW

**Comment by hvanoch** [comment]
+1 This would also enabled PHP 8.1 support.

**Comment by mbrodala** [comment]
@m-bymike can you have a look at this?

**Comment by m-bymike** [comment]
Thank you all very much, I had quite some trouble with the Travis CI integration. Now after removal, I was finally able to update everything and publish it again.

Please see [release 0.5.0](https://github.com/sclable/xml-lint/releases/tag/0.5.0), it's already available on packagist...

**Comment by mbrodala** [comment]
Thanks! :-)

**Pull request closed without merging**
