### PR TITLE
make package compatible to symfony 7

### PR DESCRIPTION
**Pull request by ischmittis**
- **Updated composer setting sto allow symfony 7 components and updated code to match latest interfaces
- **remove EOL symfony 4 ony component 4

### CODE REVIEW

**Comment by m-bymike** [comment]
Thank you for the PR, I cross-checked it locally and all tests are green.

👍

**Comment by m-bymike** [comment]
@hakan0xFF are you able to accept this PR? I'm not authorised :)

**Comment by ischmittis** [comment]
Can you create a new release to have a clear set when including this package via composer?

**Comment by hakan0xFF** [comment]
> Can you create a new release to have a clear set when including this package via composer?

A [new version](https://github.com/sclable/xml-lint/releases/tag/0.8.0) has already been released. See also https://packagist.org/packages/sclable/xml-lint

**Pull request merged**
